FROM postgres:15

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

# install dependencies
RUN apt-get update && apt-get install -y awscli

# download db dump
RUN aws s3 cp s3://qbhub/qbhub.sql /docker-entrypoint-initdb.d
