version: '3.9'
services:
  postgres:
    image: seanye24/qbhub-postgres
    restart: always
    build:
      dockerfile: Dockerfile.postgres
      context: .
      args:
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    env_file: .env
    ports:
      - ${PGPORT}:${PGPORT}
  node:
    image: seanye24/qbhub-node
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.node
      context: .
    env_file: .env
    ports:
      - ${NODE_PORT}:${NODE_PORT}
  nginx:
    image: seanye24/qbhub-nginx
    depends_on:
      - node
    restart: always
    build:
      dockerfile: Dockerfile.nginx
      context: .
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt # to serve TLS certs from
      - ./data/certbot/www:/var/www/certbot # to serve ACME challenges from
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt # to save TLS certs to
      - ./data/certbot/www:/var/www/certbot # to save ACME challenges to
    profiles:
      - certbot
