FROM node:18
WORKDIR /usr/src/app

# install dependencies
RUN apt-get update && apt-get install -y wait-for-it

# set yarn version
RUN yarn set version stable

# copy src
COPY . .

# install dependencies
RUN yarn workspace @qbhub/types install
RUN yarn workspace @qbhub/server install
RUN yarn cache clean

EXPOSE 3001
CMD [ "wait-for-it", "--timeout=0", "postgres:5432", "--", "yarn", "start" ]
