FROM postgres:15

ARG AWS_DEFAULT_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

# install system dependencies
RUN apt-get update && apt-get install -y \
  --no-install-recommends \
  awscli \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# download sql dump
RUN aws s3 cp s3://qbhub/qbhub.sql /docker-entrypoint-initdb.d
