version: '3.9'
services:
  postgres:
    restart: always
    build:
      dockerfile: Dockerfile.postgres
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  node:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.node
    ports:
      - ${NODE_PORT}:${NODE_PORT}
  nginx:
    depends_on:
      - node
    restart: always
    build:
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
