import { Category, Difficulty, Subcategory, Tournament } from '@qbhub/types';
import { objectPullWithKey } from '@qbhub/utils';

export const CATEGORIES = [
  { category: Category['Current Events'], label: 'Current Events' },
  { category: Category['Fine Arts'], label: 'Fine Arts' },
  { category: Category.Geography, label: 'Geography' },
  { category: Category.History, label: 'History' },
  { category: Category.Literature, label: 'Literature' },
  { category: Category.Mythology, label: 'Mythology' },
  { category: Category.Philosophy, label: 'Philosophy' },
  { category: Category.Religion, label: 'Religion' },
  { category: Category.Science, label: 'Science' },
  { category: Category['Social Science'], label: 'Social Science' },
  { category: Category.Trash, label: 'Trash' },
];

export const SUBCATEGORIES = [
  {
    category: Category['Current Events'],
    label: 'Current Events American',
    subcategory: Subcategory['Current Events American'],
  },
  {
    category: Category['Current Events'],
    label: 'Current Events Other',
    subcategory: Subcategory['Current Events Other'],
  },
  {
    category: Category['Fine Arts'],
    label: 'Fine Arts American',
    subcategory: Subcategory['Fine Arts American'],
  },
  {
    category: Category['Fine Arts'],
    label: 'Fine Arts Audiovisual',
    subcategory: Subcategory['Fine Arts Audiovisual'],
  },
  {
    category: Category['Fine Arts'],
    label: 'Fine Arts Auditory',
    subcategory: Subcategory['Fine Arts Auditory'],
  },
  {
    category: Category['Fine Arts'],
    label: 'Fine Arts British',
    subcategory: Subcategory['Fine Arts British'],
  },
  {
    category: Category['Fine Arts'],
    label: 'Fine Arts European',
    subcategory: Subcategory['Fine Arts European'],
  },
  {
    category: Category['Fine Arts'],
    label: 'Fine Arts Opera',
    subcategory: Subcategory['Fine Arts Opera'],
  },
  {
    category: Category['Fine Arts'],
    label: 'Fine Arts Other',
    subcategory: Subcategory['Fine Arts Other'],
  },
  {
    category: Category['Fine Arts'],
    label: 'Fine Arts Visual',
    subcategory: Subcategory['Fine Arts Visual'],
  },
  {
    category: Category['Fine Arts'],
    label: 'Fine Arts World',
    subcategory: Subcategory['Fine Arts World'],
  },
  {
    category: Category.Geography,
    label: 'Geography American',
    subcategory: Subcategory['Geography American'],
  },
  {
    category: Category.Geography,
    label: 'Geography World',
    subcategory: Subcategory['Geography World'],
  },
  {
    category: Category.History,
    label: 'History American',
    subcategory: Subcategory['History American'],
  },
  {
    category: Category.History,
    label: 'History British',
    subcategory: Subcategory['History British'],
  },
  {
    category: Category.History,
    label: 'History Classical',
    subcategory: Subcategory['History Classical'],
  },
  {
    category: Category.History,
    label: 'History European',
    subcategory: Subcategory['History European'],
  },
  {
    category: Category.History,
    label: 'History Other',
    subcategory: Subcategory['History Other'],
  },
  {
    category: Category.History,
    label: 'History World',
    subcategory: Subcategory['History World'],
  },
  {
    category: Category.Literature,
    label: 'Literature American',
    subcategory: Subcategory['Literature American'],
  },
  {
    category: Category.Literature,
    label: 'Literature British',
    subcategory: Subcategory['Literature British'],
  },
  {
    category: Category.Literature,
    label: 'Literature Classical',
    subcategory: Subcategory['Literature Classical'],
  },
  {
    category: Category.Literature,
    label: 'Literature European',
    subcategory: Subcategory['Literature European'],
  },
  {
    category: Category.Literature,
    label: 'Literature Other',
    subcategory: Subcategory['Literature Other'],
  },
  {
    category: Category.Literature,
    label: 'Literature World',
    subcategory: Subcategory['Literature World'],
  },
  {
    category: Category.Mythology,
    label: 'Mythology American',
    subcategory: Subcategory['Mythology American'],
  },
  {
    category: Category.Mythology,
    label: 'Mythology Chinese',
    subcategory: Subcategory['Mythology Chinese'],
  },
  {
    category: Category.Mythology,
    label: 'Mythology Egyptian',
    subcategory: Subcategory['Mythology Egyptian'],
  },
  {
    category: Category.Mythology,
    label: 'Mythology Greco-Roman',
    subcategory: Subcategory['Mythology Greco-Roman'],
  },
  {
    category: Category.Mythology,
    label: 'Mythology Indian',
    subcategory: Subcategory['Mythology Indian'],
  },
  {
    category: Category.Mythology,
    label: 'Mythology Japanese',
    subcategory: Subcategory['Mythology Japanese'],
  },
  {
    category: Category.Mythology,
    label: 'Mythology Norse',
    subcategory: Subcategory['Mythology Norse'],
  },
  {
    category: Category.Mythology,
    label: 'Mythology Other',
    subcategory: Subcategory['Mythology Other'],
  },
  {
    category: Category.Mythology,
    label: 'Mythology Other East Asian',
    subcategory: Subcategory['Mythology Other East Asian'],
  },
  {
    category: Category.Philosophy,
    label: 'Philosophy American',
    subcategory: Subcategory['Philosophy American'],
  },
  {
    category: Category.Philosophy,
    label: 'Philosophy Classical',
    subcategory: Subcategory['Philosophy Classical'],
  },
  {
    category: Category.Philosophy,
    label: 'Philosophy East Asian',
    subcategory: Subcategory['Philosophy East Asian'],
  },
  {
    category: Category.Philosophy,
    label: 'Philosophy European',
    subcategory: Subcategory['Philosophy European'],
  },
  {
    category: Category.Philosophy,
    label: 'Philosophy Other',
    subcategory: Subcategory['Philosophy Other'],
  },
  {
    category: Category.Religion,
    label: 'Religion American',
    subcategory: Subcategory['Religion American'],
  },
  {
    category: Category.Religion,
    label: 'Religion Christianity',
    subcategory: Subcategory['Religion Christianity'],
  },
  {
    category: Category.Religion,
    label: 'Religion East Asian',
    subcategory: Subcategory['Religion East Asian'],
  },
  {
    category: Category.Religion,
    label: 'Religion Islam',
    subcategory: Subcategory['Religion Islam'],
  },
  {
    category: Category.Religion,
    label: 'Religion Judaism',
    subcategory: Subcategory['Religion Judaism'],
  },
  {
    category: Category.Religion,
    label: 'Religion Other',
    subcategory: Subcategory['Religion Other'],
  },
  {
    category: Category.Science,
    label: 'Science American',
    subcategory: Subcategory['Science American'],
  },
  {
    category: Category.Science,
    label: 'Science Biology',
    subcategory: Subcategory['Science Biology'],
  },
  {
    category: Category.Science,
    label: 'Science Chemistry',
    subcategory: Subcategory['Science Chemistry'],
  },
  {
    category: Category.Science,
    label: 'Science Computer Science',
    subcategory: Subcategory['Science Computer Science'],
  },
  {
    category: Category.Science,
    label: 'Science Math',
    subcategory: Subcategory['Science Math'],
  },
  {
    category: Category.Science,
    label: 'Science Other',
    subcategory: Subcategory['Science Other'],
  },
  {
    category: Category.Science,
    label: 'Science Physics',
    subcategory: Subcategory['Science Physics'],
  },
  {
    category: Category.Science,
    label: 'Science World',
    subcategory: Subcategory['Science World'],
  },
  {
    category: Category['Social Science'],
    label: 'Social Science American',
    subcategory: Subcategory['Social Science American'],
  },
  {
    category: Category['Social Science'],
    label: 'Social Science Anthropology',
    subcategory: Subcategory['Social Science Anthropology'],
  },
  {
    category: Category['Social Science'],
    label: 'Social Science Economics',
    subcategory: Subcategory['Social Science Economics'],
  },
  {
    category: Category['Social Science'],
    label: 'Social Science Linguistics',
    subcategory: Subcategory['Social Science Linguistics'],
  },
  {
    category: Category['Social Science'],
    label: 'Social Science Other',
    subcategory: Subcategory['Social Science Other'],
  },
  {
    category: Category['Social Science'],
    label: 'Social Science Political Science',
    subcategory: Subcategory['Social Science Political Science'],
  },
  {
    category: Category['Social Science'],
    label: 'Social Science Psychology',
    subcategory: Subcategory['Social Science Psychology'],
  },
  {
    category: Category['Social Science'],
    label: 'Social Science Sociology',
    subcategory: Subcategory['Social Science Sociology'],
  },
  {
    category: Category.Trash,
    label: 'Trash American',
    subcategory: Subcategory['Trash American'],
  },
  {
    category: Category.Trash,
    label: 'Trash Movies',
    subcategory: Subcategory['Trash Movies'],
  },
  {
    category: Category.Trash,
    label: 'Trash Music',
    subcategory: Subcategory['Trash Music'],
  },
  {
    category: Category.Trash,
    label: 'Trash Other',
    subcategory: Subcategory['Trash Other'],
  },
  {
    category: Category.Trash,
    label: 'Trash Sports',
    subcategory: Subcategory['Trash Sports'],
  },
  {
    category: Category.Trash,
    label: 'Trash Television',
    subcategory: Subcategory['Trash Television'],
  },
  {
    category: Category.Trash,
    label: 'Trash Video Games',
    subcategory: Subcategory['Trash Video Games'],
  },
];

export const DIFFICULTIES = [
  { difficulty: Difficulty['Middle School'], label: 'Middle School' },
  { difficulty: Difficulty['Easy High School'], label: 'Easy High School' },
  {
    difficulty: Difficulty['Regular High School'],
    label: 'Regular High School',
  },
  { difficulty: Difficulty['Hard High School'], label: 'Hard High School' },
  {
    difficulty: Difficulty['National High School'],
    label: 'National High School',
  },
  { difficulty: Difficulty['Easy College'], label: 'Easy College' },
  { difficulty: Difficulty['Regular College'], label: 'Regular College' },
  { difficulty: Difficulty['Hard College'], label: 'Hard College' },
  { difficulty: Difficulty.Open, label: 'Open' },
];

export const TOURNAMENTS = [
  {
    difficulty: Difficulty['Regular High School'],
    label: '2020 CALISTO',
    tournament: Tournament['2020 CALISTO'],
    year: 2020,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2020 Oxford Online',
    tournament: Tournament['2020 Oxford Online'],
    year: 2020,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2020 Terrapin',
    tournament: Tournament['2020 Terrapin'],
    year: 2020,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: 'Tree of Clues',
    tournament: Tournament['Tree of Clues'],
    year: 2020,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2019 ACF Fall',
    tournament: Tournament['2019 ACF Fall'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2019 ACF Regionals',
    tournament: Tournament['2019 ACF Regionals'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2019 BHSAT',
    tournament: Tournament['2019 BHSAT'],
    year: 2019,
  },
  {
    difficulty: Difficulty.Open,
    label: '2019 Chicago Open',
    tournament: Tournament['2019 Chicago Open'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2019 Early Fall Tournament (EFT)',
    tournament: Tournament['2019 Early Fall Tournament (EFT)'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2019 HFT XIV',
    tournament: Tournament['2019 HFT XIV'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2019 ILLIAC',
    tournament: Tournament['2019 ILLIAC'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2019 LOGIC',
    tournament: Tournament['2019 LOGIC'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2019 NASAT',
    tournament: Tournament['2019 NASAT'],
    year: 2019,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2019 PACE NSC',
    tournament: Tournament['2019 PACE NSC'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2019 PIANO',
    tournament: Tournament['2019 PIANO'],
    year: 2019,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2019 Prison Bowl',
    tournament: Tournament['2019 Prison Bowl'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2019 Richard Montgomery Blair Academic Tournament',
    tournament: Tournament['2019 Richard Montgomery Blair Academic Tournament'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2019 Spartan Housewrite',
    tournament: Tournament['2019 Spartan Housewrite'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2019 Terrapin',
    tournament: Tournament['2019 Terrapin'],
    year: 2019,
  },
  {
    difficulty: Difficulty.Open,
    label: '2019 The Unanswered Question',
    tournament: Tournament['2019 The Unanswered Question'],
    year: 2019,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2018 ACF Fall',
    tournament: Tournament['2018 ACF Fall'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2018 ACF Nationals',
    tournament: Tournament['2018 ACF Nationals'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2018 ACF Regionals',
    tournament: Tournament['2018 ACF Regionals'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2018 BHSAT',
    tournament: Tournament['2018 BHSAT'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2018 Cambridge Open',
    tournament: Tournament['2018 Cambridge Open'],
    year: 2018,
  },
  {
    difficulty: Difficulty.Open,
    label: '2018 Chicago Open',
    tournament: Tournament['2018 Chicago Open'],
    year: 2018,
  },
  {
    difficulty: Difficulty.Open,
    label: '2018 Chicago Open Trash',
    tournament: Tournament['2018 Chicago Open Trash'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2018 CMST',
    tournament: Tournament['2018 CMST'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2018 Early Fall Tournament (EFT)',
    tournament: Tournament['2018 Early Fall Tournament (EFT)'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2018 FACTS',
    tournament: Tournament['2018 FACTS'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2018 Great Lakes Regional Academic Championship (GLRAC)',
    tournament:
      Tournament['2018 Great Lakes Regional Academic Championship (GLRAC)'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2018 HFT XIII',
    tournament: Tournament['2018 HFT XIII'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2018 Historature',
    tournament: Tournament['2018 Historature'],
    year: 2018,
  },
  {
    difficulty: Difficulty.Open,
    label: '2018 HORROR 1',
    tournament: Tournament['2018 HORROR 1'],
    year: 2018,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2018 IMSAnity 5',
    tournament: Tournament['2018 IMSAnity 5'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2018 Montgomery Blair Academic Tournament (MBAT)',
    tournament: Tournament['2018 Montgomery Blair Academic Tournament (MBAT)'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2018 NASAT',
    tournament: Tournament['2018 NASAT'],
    year: 2018,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2018 PACE NSC',
    tournament: Tournament['2018 PACE NSC'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2018 Penn Bowl',
    tournament: Tournament['2018 Penn Bowl'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2018 Prison Bowl XI',
    tournament: Tournament['2018 Prison Bowl XI'],
    year: 2018,
  },
  {
    difficulty: Difficulty.Open,
    label: '2018 RAPTURE',
    tournament: Tournament['2018 RAPTURE'],
    year: 2018,
  },
  {
    difficulty: Difficulty.Open,
    label: '2018 Scattergories 2',
    tournament: Tournament['2018 Scattergories 2'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2018 SMT',
    tournament: Tournament['2018 SMT'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2018 Sun God Invitational',
    tournament: Tournament['2018 Sun God Invitational'],
    year: 2018,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: 'FILM',
    tournament: Tournament.FILM,
    year: 2018,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: 'Words and Objects',
    tournament: Tournament['Words and Objects'],
    year: 2018,
  },
  {
    difficulty: Difficulty.Open,
    label: 'WORLDSTAR',
    tournament: Tournament.WORLDSTAR,
    year: 2018,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2017 ACF Fall',
    tournament: Tournament['2017 ACF Fall'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2017 ACF Nationals',
    tournament: Tournament['2017 ACF Nationals'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2017 ACF Regionals',
    tournament: Tournament['2017 ACF Regionals'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2017 BHSAT',
    tournament: Tournament['2017 BHSAT'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: '2017 Chicago Open',
    tournament: Tournament['2017 Chicago Open'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2017 Early Fall Tournament (EFT)',
    tournament: Tournament['2017 Early Fall Tournament (EFT)'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2017 EMT',
    tournament: Tournament['2017 EMT'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: '2017 Fine Arts Common Links',
    tournament: Tournament['2017 Fine Arts Common Links'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: '2017 FRENCH',
    tournament: Tournament['2017 FRENCH'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: '2017 Geography Monstrosity',
    tournament: Tournament['2017 Geography Monstrosity'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2017 GSAC XXV',
    tournament: Tournament['2017 GSAC XXV'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2017 HFT XII',
    tournament: Tournament['2017 HFT XII'],
    year: 2017,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2017 History Bee Nationals',
    tournament: Tournament['2017 History Bee Nationals'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: "2017 It's Lit",
    tournament: Tournament["2017 It's Lit"],
    year: 2017,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2017 JAKOB',
    tournament: Tournament['2017 JAKOB'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: '2017 Jordaens Visual Arts',
    tournament: Tournament['2017 Jordaens Visual Arts'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: '2017 Letras',
    tournament: Tournament['2017 Letras'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2017 LIST (Ladue Invitational Spring Tournament) VI',
    tournament:
      Tournament['2017 LIST (Ladue Invitational Spring Tournament) VI'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2017 MASSOLIT',
    tournament: Tournament['2017 MASSOLIT'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: '2017 Math Monstrosity',
    tournament: Tournament['2017 Math Monstrosity'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2017 NASAT',
    tournament: Tournament['2017 NASAT'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: '2017 Naveed Bork Memorial Tournament',
    tournament: Tournament['2017 Naveed Bork Memorial Tournament'],
    year: 2017,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2017 PACE NSC',
    tournament: Tournament['2017 PACE NSC'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2017 Penn Bowl',
    tournament: Tournament['2017 Penn Bowl'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2017 Philly Cheesteak',
    tournament: Tournament['2017 Philly Cheesteak'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2017 Prison Bowl X',
    tournament: Tournament['2017 Prison Bowl X'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2017 RMBCT',
    tournament: Tournament['2017 RMBCT'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: '2017 Scattergories',
    tournament: Tournament['2017 Scattergories'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2017 Sivakumar Day Inter-Nationals',
    tournament: Tournament['2017 Sivakumar Day Inter-Nationals'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: '2017 (This) Tournament is a Crime',
    tournament: Tournament['2017 (This) Tournament is a Crime'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2017 WAO II',
    tournament: Tournament['2017 WAO II'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2017 WHAQ II',
    tournament: Tournament['2017 WHAQ II'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2017 XENOPHON',
    tournament: Tournament['2017 XENOPHON'],
    year: 2017,
  },
  {
    difficulty: Difficulty.Open,
    label: 'GRAB BAG',
    tournament: Tournament['GRAB BAG'],
    year: 2017,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2016 A Bit of Lit',
    tournament: Tournament['2016 A Bit of Lit'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2016 ACF Fall',
    tournament: Tournament['2016 ACF Fall'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2016 ACF Nationals',
    tournament: Tournament['2016 ACF Nationals'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2016 ACF Regionals',
    tournament: Tournament['2016 ACF Regionals'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2016 ACF Regionals ',
    tournament: Tournament['2016 ACF Regionals '],
    year: 2016,
  },
  {
    difficulty: Difficulty.Open,
    label: '2016 A Culture of Improvement',
    tournament: Tournament['2016 A Culture of Improvement'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2016 BHSAT',
    tournament: Tournament['2016 BHSAT'],
    year: 2016,
  },
  {
    difficulty: Difficulty.Open,
    label: '2016 Chicago Open',
    tournament: Tournament['2016 Chicago Open'],
    year: 2016,
  },
  {
    difficulty: Difficulty.Open,
    label: '2016 Christmas Present',
    tournament: Tournament['2016 Christmas Present'],
    year: 2016,
  },
  {
    difficulty: Difficulty.Open,
    label: '2016 CLEAR II',
    tournament: Tournament['2016 CLEAR II'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2016 Delta Burke',
    tournament: Tournament['2016 Delta Burke'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2016 Early Fall Tournament (EFT)',
    tournament: Tournament['2016 Early Fall Tournament (EFT)'],
    year: 2016,
  },
  {
    difficulty: Difficulty.Open,
    label: '2016 Geography Monstrosity',
    tournament: Tournament['2016 Geography Monstrosity'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2016 HFT XI',
    tournament: Tournament['2016 HFT XI'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2016 Listory',
    tournament: Tournament['2016 Listory'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2016 MLK',
    tournament: Tournament['2016 MLK'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2016 MUT',
    tournament: Tournament['2016 MUT'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2016 MYSTERIUM',
    tournament: Tournament['2016 MYSTERIUM'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2016 NASAT',
    tournament: Tournament['2016 NASAT'],
    year: 2016,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2016 PACE NSC',
    tournament: Tournament['2016 PACE NSC'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2016 Penn Bowl',
    tournament: Tournament['2016 Penn Bowl'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2016 Scobol Solo',
    tournament: Tournament['2016 Scobol Solo'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Middle School'],
    label: '2016 SCOP MS 6',
    tournament: Tournament['2016 SCOP MS 6'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '"2016 ""stanford housewrite"""',
    tournament: Tournament['"2016 ""stanford housewrite"""'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2016 Terrapin',
    tournament: Tournament['2016 Terrapin'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2016 WAO',
    tournament: Tournament['2016 WAO'],
    year: 2016,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2016 WHAQ I',
    tournament: Tournament['2016 WHAQ I'],
    year: 2016,
  },
  {
    difficulty: Difficulty.Open,
    label: 'GRAPHIC',
    tournament: Tournament.GRAPHIC,
    year: 2016,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2015 ACF Fall',
    tournament: Tournament['2015 ACF Fall'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2015 ACF Nationals',
    tournament: Tournament['2015 ACF Nationals'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2015 ACF Regionals',
    tournament: Tournament['2015 ACF Regionals'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2015 ACF Regionals ',
    tournament: Tournament['2015 ACF Regionals '],
    year: 2015,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2015 BASK',
    tournament: Tournament['2015 BASK'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2015 BHSAT',
    tournament: Tournament['2015 BHSAT'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: "2015 BISB (Brookwood Invitational Scholars' Bowl)",
    tournament: Tournament["2015 BISB (Brookwood Invitational Scholars' Bowl)"],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 Chicago Open',
    tournament: Tournament['2015 Chicago Open'],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 Chicago Open History',
    tournament: Tournament['2015 Chicago Open History'],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 Chicago Open Visual Arts',
    tournament: Tournament['2015 Chicago Open Visual Arts'],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 Claude Shannon Memorial Tournament',
    tournament: Tournament['2015 Claude Shannon Memorial Tournament'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2015 Delta Burke',
    tournament: Tournament['2015 Delta Burke'],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 Geography Monstrosity',
    tournament: Tournament['2015 Geography Monstrosity'],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 George Oppen',
    tournament: Tournament['2015 George Oppen'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2015 GSAC XXIII',
    tournament: Tournament['2015 GSAC XXIII'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2015 HFT X',
    tournament: Tournament['2015 HFT X'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2015 Maryland Fall',
    tournament: Tournament['2015 Maryland Fall'],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 Missouri Open',
    tournament: Tournament['2015 Missouri Open'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2015 MUT',
    tournament: Tournament['2015 MUT'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2015 NASAT',
    tournament: Tournament['2015 NASAT'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2015 NASAT ',
    tournament: Tournament['2015 NASAT '],
    year: 2015,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2015 PACE NSC',
    tournament: Tournament['2015 PACE NSC'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2015 Penn Bowl',
    tournament: Tournament['2015 Penn Bowl'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2015 Prison Bowl VIII',
    tournament: Tournament['2015 Prison Bowl VIII'],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 RILKE',
    tournament: Tournament['2015 RILKE'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Middle School'],
    label: '2015 SCOP MS 5',
    tournament: Tournament['2015 SCOP MS 5'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2015 SHEIKH',
    tournament: Tournament['2015 SHEIKH'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2015 STIMPY',
    tournament: Tournament['2015 STIMPY'],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 VCU Open',
    tournament: Tournament['2015 VCU Open'],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 VICO',
    tournament: Tournament['2015 VICO'],
    year: 2015,
  },
  {
    difficulty: Difficulty.Open,
    label: '2015 We Have Never Been Modern',
    tournament: Tournament['2015 We Have Never Been Modern'],
    year: 2015,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2014 ACF Fall',
    tournament: Tournament['2014 ACF Fall'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2014 ACF Fall ',
    tournament: Tournament['2014 ACF Fall '],
    year: 2014,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2014 ACF Nationals',
    tournament: Tournament['2014 ACF Nationals'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 ACF Regionals',
    tournament: Tournament['2014 ACF Regionals'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 ACF Regionals 2014',
    tournament: Tournament['2014 ACF Regionals 2014'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2014 BELLOCO',
    tournament: Tournament['2014 BELLOCO'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2014 BHSAT',
    tournament: Tournament['2014 BHSAT'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2014 Cane Ridge Revival',
    tournament: Tournament['2014 Cane Ridge Revival'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 Cheyne American History People',
    tournament: Tournament['2014 Cheyne American History People'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 Cheyne American Thought',
    tournament: Tournament['2014 Cheyne American Thought'],
    year: 2014,
  },
  {
    difficulty: Difficulty.Open,
    label: '2014 Chicago Open',
    tournament: Tournament['2014 Chicago Open'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2014 College History Bowl',
    tournament: Tournament['2014 College History Bowl'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 DEES',
    tournament: Tournament['2014 DEES'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2014 Delta Burke',
    tournament: Tournament['2014 Delta Burke'],
    year: 2014,
  },
  {
    difficulty: Difficulty.Open,
    label: '2014 Geography Monstrosity',
    tournament: Tournament['2014 Geography Monstrosity'],
    year: 2014,
  },
  {
    difficulty: Difficulty.Open,
    label: '2014 Gorilla Lit',
    tournament: Tournament['2014 Gorilla Lit'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2014 GSAC',
    tournament: Tournament['2014 GSAC'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2014 ICCS',
    tournament: Tournament['2014 ICCS'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2014 LIST IV',
    tournament: Tournament['2014 LIST IV'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2014 Masonic',
    tournament: Tournament['2014 Masonic'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 Mavis Gallant Memorial',
    tournament: Tournament['2014 Mavis Gallant Memorial'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 Michigan Fall Tournament',
    tournament: Tournament['2014 Michigan Fall Tournament'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2014 MUT',
    tournament: Tournament['2014 MUT'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 NASAT',
    tournament: Tournament['2014 NASAT'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 NASAT ',
    tournament: Tournament['2014 NASAT '],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2014 New Trier Scobol Solo',
    tournament: Tournament['2014 New Trier Scobol Solo'],
    year: 2014,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2014 PACE NSC',
    tournament: Tournament['2014 PACE NSC'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 Padawan',
    tournament: Tournament['2014 Padawan'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 PADAWAN',
    tournament: Tournament['2014 PADAWAN'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 Penn Bowl',
    tournament: Tournament['2014 Penn Bowl'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2014 Prison Bowl',
    tournament: Tournament['2014 Prison Bowl'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2014 SCOP Novice',
    tournament: Tournament['2014 SCOP Novice'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2014 SUBMIT',
    tournament: Tournament['2014 SUBMIT'],
    year: 2014,
  },
  {
    difficulty: Difficulty.Open,
    label: '2014 VCU Open',
    tournament: Tournament['2014 VCU Open'],
    year: 2014,
  },
  {
    difficulty: Difficulty.Open,
    label: '2014 VCU Open ',
    tournament: Tournament['2014 VCU Open '],
    year: 2014,
  },
  {
    difficulty: Difficulty.Open,
    label: 'Lederberg Memorial Science Tournament 2: Daughter Cell',
    tournament:
      Tournament['Lederberg Memorial Science Tournament 2: Daughter Cell'],
    year: 2014,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2013 ACF Fall',
    tournament: Tournament['2013 ACF Fall'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2013 ACF Nationals',
    tournament: Tournament['2013 ACF Nationals'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2013 ACF Nationals ',
    tournament: Tournament['2013 ACF Nationals '],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2013 ACF Regionals',
    tournament: Tournament['2013 ACF Regionals'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2013 Angels in the Architecture',
    tournament: Tournament['2013 Angels in the Architecture'],
    year: 2013,
  },
  {
    difficulty: Difficulty.Open,
    label: '2013 Arrabal',
    tournament: Tournament['2013 Arrabal'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2013 BHSAT',
    tournament: Tournament['2013 BHSAT'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2013 Brookwood Invitational Scholars Bowl',
    tournament: Tournament['2013 Brookwood Invitational Scholars Bowl'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2013 Cheyne American History',
    tournament: Tournament['2013 Cheyne American History'],
    year: 2013,
  },
  {
    difficulty: Difficulty.Open,
    label: '2013 Chicago Open',
    tournament: Tournament['2013 Chicago Open'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Middle School'],
    label: '2013 Collaborative MS Tournament',
    tournament: Tournament['2013 Collaborative MS Tournament'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2013 Collegiate Novice',
    tournament: Tournament['2013 Collegiate Novice'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2013 Delta Burke',
    tournament: Tournament['2013 Delta Burke'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2013 Dragoon',
    tournament: Tournament['2013 Dragoon'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2013 DRAGOON',
    tournament: Tournament['2013 DRAGOON'],
    year: 2013,
  },
  {
    difficulty: Difficulty.Open,
    label: '2013 Geography Monstrosity',
    tournament: Tournament['2013 Geography Monstrosity'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2013 GSAC',
    tournament: Tournament['2013 GSAC'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2013 JAMES',
    tournament: Tournament['2013 JAMES'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2013 LIST III',
    tournament: Tournament['2013 LIST III'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2013 Maggie Walker GSAC',
    tournament: Tournament['2013 Maggie Walker GSAC'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2013 Michigan Fall Tournament',
    tournament: Tournament['2013 Michigan Fall Tournament'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2013 MUT',
    tournament: Tournament['2013 MUT'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2013 NASAT',
    tournament: Tournament['2013 NASAT'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2013 NTSS',
    tournament: Tournament['2013 NTSS'],
    year: 2013,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2013 PACE NSC',
    tournament: Tournament['2013 PACE NSC'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2013 Penn Bowl',
    tournament: Tournament['2013 Penn Bowl'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2013 Prison Bowl',
    tournament: Tournament['2013 Prison Bowl'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: "2013 Schindler's Lit",
    tournament: Tournament["2013 Schindler's Lit"],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2013 Scobol Solo',
    tournament: Tournament['2013 Scobol Solo'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2013 SCOP Novice',
    tournament: Tournament['2013 SCOP Novice'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2013 Terrapin',
    tournament: Tournament['2013 Terrapin'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2013 VCU Closed',
    tournament: Tournament['2013 VCU Closed'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2013 VCU Closed ',
    tournament: Tournament['2013 VCU Closed '],
    year: 2013,
  },
  {
    difficulty: Difficulty.Open,
    label: '2013 VCU Open',
    tournament: Tournament['2013 VCU Open'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2013 Western Invitational Tournament',
    tournament: Tournament['2013 Western Invitational Tournament'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: 'Scobol Solo',
    tournament: Tournament['Scobol Solo'],
    year: 2013,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 2012 Penn-ance',
    tournament: Tournament['2012 2012 Penn-ance'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2012 ACF Fall',
    tournament: Tournament['2012 ACF Fall'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2012 ACF Nationals',
    tournament: Tournament['2012 ACF Nationals'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2012 ACF Nationals ',
    tournament: Tournament['2012 ACF Nationals '],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 ACF Regionals',
    tournament: Tournament['2012 ACF Regionals'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 ACF Regionals ',
    tournament: Tournament['2012 ACF Regionals '],
    year: 2012,
  },
  {
    difficulty: Difficulty.Open,
    label: '2012 ANFORTAS',
    tournament: Tournament['2012 ANFORTAS'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 BARGE',
    tournament: Tournament['2012 BARGE'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2012 BHSAT',
    tournament: Tournament['2012 BHSAT'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 Cheyne American History',
    tournament: Tournament['2012 Cheyne American History'],
    year: 2012,
  },
  {
    difficulty: Difficulty.Open,
    label: '2012 Chicago Open',
    tournament: Tournament['2012 Chicago Open'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Middle School'],
    label: '2012 Collaborative MS Tournament',
    tournament: Tournament['2012 Collaborative MS Tournament'],
    year: 2012,
  },
  {
    difficulty: Difficulty.Open,
    label: '2012 College History Bowl',
    tournament: Tournament['2012 College History Bowl'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2012 Collegiate Novice',
    tournament: Tournament['2012 Collegiate Novice'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2012 Delta Burke',
    tournament: Tournament['2012 Delta Burke'],
    year: 2012,
  },
  {
    difficulty: Difficulty.Open,
    label: '2012 Geography Monstrosity',
    tournament: Tournament['2012 Geography Monstrosity'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2012 Harvard Fall Tournament',
    tournament: Tournament['2012 Harvard Fall Tournament'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 Illinois Fall Tournament',
    tournament: Tournament['2012 Illinois Fall Tournament'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 KABO',
    tournament: Tournament['2012 KABO'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2012 LIST (Ladue Invitational Spring Tournament)',
    tournament: Tournament['2012 LIST (Ladue Invitational Spring Tournament)'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2012 Maggie Walker GSAC',
    tournament: Tournament['2012 Maggie Walker GSAC'],
    year: 2012,
  },
  {
    difficulty: Difficulty.Open,
    label: '2012 Minnesota Open',
    tournament: Tournament['2012 Minnesota Open'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2012 MUT',
    tournament: Tournament['2012 MUT'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 NASAT',
    tournament: Tournament['2012 NASAT'],
    year: 2012,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2012 PACE NSC',
    tournament: Tournament['2012 PACE NSC'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 Peaceful Resolution',
    tournament: Tournament['2012 Peaceful Resolution'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 Penn-ance',
    tournament: Tournament['2012 Penn-ance'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 Penn Bowl',
    tournament: Tournament['2012 Penn Bowl'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2012 Prison Bowl',
    tournament: Tournament['2012 Prison Bowl'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2012 Prison Bowl ',
    tournament: Tournament['2012 Prison Bowl '],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 QUARK',
    tournament: Tournament['2012 QUARK'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2012 RAVE',
    tournament: Tournament['2012 RAVE'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2012 SCOP Novice',
    tournament: Tournament['2012 SCOP Novice'],
    year: 2012,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2012 WELD',
    tournament: Tournament['2012 WELD'],
    year: 2012,
  },
  {
    difficulty: Difficulty.Open,
    label: '2012 YMIR',
    tournament: Tournament['2012 YMIR'],
    year: 2012,
  },
  {
    difficulty: Difficulty.Open,
    label: '2011 2011 Minnesota Open',
    tournament: Tournament['2011 2011 Minnesota Open'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2011 ACF Fall',
    tournament: Tournament['2011 ACF Fall'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2011 ACF Fall ',
    tournament: Tournament['2011 ACF Fall '],
    year: 2011,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2011 ACF Nationals',
    tournament: Tournament['2011 ACF Nationals'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2011 ACF Regionals',
    tournament: Tournament['2011 ACF Regionals'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2011 BHSAT',
    tournament: Tournament['2011 BHSAT'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2011 Cheyne 1980s American History',
    tournament: Tournament['2011 Cheyne 1980s American History'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2011 Cheyne American History',
    tournament: Tournament['2011 Cheyne American History'],
    year: 2011,
  },
  {
    difficulty: Difficulty.Open,
    label: '2011 Chicago Open',
    tournament: Tournament['2011 Chicago Open'],
    year: 2011,
  },
  {
    difficulty: Difficulty.Open,
    label: '2011 Chicago Open History',
    tournament: Tournament['2011 Chicago Open History'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Middle School'],
    label: '2011 Collaborative MS Tournament',
    tournament: Tournament['2011 Collaborative MS Tournament'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2011 Collegiate Novice',
    tournament: Tournament['2011 Collegiate Novice'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2011 Delta Burke',
    tournament: Tournament['2011 Delta Burke'],
    year: 2011,
  },
  {
    difficulty: Difficulty.Open,
    label: '2011 Geography Monstrosity',
    tournament: Tournament['2011 Geography Monstrosity'],
    year: 2011,
  },
  {
    difficulty: Difficulty.Open,
    label: '2011 Guerrilla at ICT',
    tournament: Tournament['2011 Guerrilla at ICT'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2011 HSAPQ Colonia 2',
    tournament: Tournament['2011 HSAPQ Colonia 2'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2011 HSAPQ National History Bowl',
    tournament: Tournament['2011 HSAPQ National History Bowl'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2011 HSAPQ Tournament 15',
    tournament: Tournament['2011 HSAPQ Tournament 15'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2011 HSAPQ Tournament 16',
    tournament: Tournament['2011 HSAPQ Tournament 16'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2011 HSAPQ Tournament 17',
    tournament: Tournament['2011 HSAPQ Tournament 17'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2011 HSAPQ VHSL Districts',
    tournament: Tournament['2011 HSAPQ VHSL Districts'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2011 HSAPQ VHSL Regionals',
    tournament: Tournament['2011 HSAPQ VHSL Regionals'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2011 HSAPQ VHSL Regular Season',
    tournament: Tournament['2011 HSAPQ VHSL Regular Season'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2011 HSAPQ VHSL States',
    tournament: Tournament['2011 HSAPQ VHSL States'],
    year: 2011,
  },
  {
    difficulty: Difficulty.Open,
    label: '2011 Illinois Open',
    tournament: Tournament['2011 Illinois Open'],
    year: 2011,
  },
  {
    difficulty: Difficulty.Open,
    label: '2011 Illinois Wissenschaftslehre',
    tournament: Tournament['2011 Illinois Wissenschaftslehre'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2011 Maggie Walker GSAC',
    tournament: Tournament['2011 Maggie Walker GSAC'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2011 MAGNI',
    tournament: Tournament['2011 MAGNI'],
    year: 2011,
  },
  {
    difficulty: Difficulty.Open,
    label: '2011 Minnesota Open',
    tournament: Tournament['2011 Minnesota Open'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2011 Missiles of October',
    tournament: Tournament['2011 Missiles of October'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2011 MUT',
    tournament: Tournament['2011 MUT'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2011 NASAT',
    tournament: Tournament['2011 NASAT'],
    year: 2011,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2011 PACE NSC',
    tournament: Tournament['2011 PACE NSC'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2011 Penn Bowl',
    tournament: Tournament['2011 Penn Bowl'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2011 Prison Bowl',
    tournament: Tournament['2011 Prison Bowl'],
    year: 2011,
  },
  {
    difficulty: Difficulty.Open,
    label: '2011 SACK',
    tournament: Tournament['2011 SACK'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2011 SCOP Novice',
    tournament: Tournament['2011 SCOP Novice'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2011 St. Anselms and Torrey Pines',
    tournament: Tournament['2011 St. Anselms and Torrey Pines'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2011 Terrapin Invitational',
    tournament: Tournament['2011 Terrapin Invitational'],
    year: 2011,
  },
  {
    difficulty: Difficulty.Open,
    label: '2011 The Bob Loblaw Law Bowl',
    tournament: Tournament['2011 The Bob Loblaw Law Bowl'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2011 VCU Open',
    tournament: Tournament['2011 VCU Open'],
    year: 2011,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2010 2010 ACF Fall',
    tournament: Tournament['2010 2010 ACF Fall'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2010 ACF Fall',
    tournament: Tournament['2010 ACF Fall'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2010 ACF Nationals',
    tournament: Tournament['2010 ACF Nationals'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2010 ACF Novice',
    tournament: Tournament['2010 ACF Novice'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2010 ACF Regionals',
    tournament: Tournament['2010 ACF Regionals'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2010 ACF Winter',
    tournament: Tournament['2010 ACF Winter'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 ANGST',
    tournament: Tournament['2010 ANGST'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 BELFAST Arts',
    tournament: Tournament['2010 BELFAST Arts'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 Chicago Open',
    tournament: Tournament['2010 Chicago Open'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 Chicago Open Arts',
    tournament: Tournament['2010 Chicago Open Arts'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 Chicago Open Literature',
    tournament: Tournament['2010 Chicago Open Literature'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Middle School'],
    label: '2010 Collaborative MS Tournament',
    tournament: Tournament['2010 Collaborative MS Tournament'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2010 Delta Burke',
    tournament: Tournament['2010 Delta Burke'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2010 Early Fall Tournament (EFT)',
    tournament: Tournament['2010 Early Fall Tournament (EFT)'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2010 Fall Kickoff Tournament',
    tournament: Tournament['2010 Fall Kickoff Tournament'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2010 Fall Novice',
    tournament: Tournament['2010 Fall Novice'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2010 GDS Ben Cooper Memorial',
    tournament: Tournament['2010 GDS Ben Cooper Memorial'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 Geography Monstrosity 2',
    tournament: Tournament['2010 Geography Monstrosity 2'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2010 Guerrilla at ICT',
    tournament: Tournament['2010 Guerrilla at ICT'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 Harvard International',
    tournament: Tournament['2010 Harvard International'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 Julius Civilis Classics Tournament',
    tournament: Tournament['2010 Julius Civilis Classics Tournament'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2010 Maggie Walker GSAC',
    tournament: Tournament['2010 Maggie Walker GSAC'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2010 MELD',
    tournament: Tournament['2010 MELD'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 Minnesota Open',
    tournament: Tournament['2010 Minnesota Open'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2010 MUT',
    tournament: Tournament['2010 MUT'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2010 NASAT',
    tournament: Tournament['2010 NASAT'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2010 NTSS',
    tournament: Tournament['2010 NTSS'],
    year: 2010,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2010 PACE NSC',
    tournament: Tournament['2010 PACE NSC'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2010 Penn Bowl',
    tournament: Tournament['2010 Penn Bowl'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2010 Princeton Buzzerfest',
    tournament: Tournament['2010 Princeton Buzzerfest'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2010 Prison Bowl',
    tournament: Tournament['2010 Prison Bowl'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2010 SCOP Novice',
    tournament: Tournament['2010 SCOP Novice'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2010 Sun n Fun',
    tournament: Tournament['2010 Sun n Fun'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2010 THUNDER II',
    tournament: Tournament['2010 THUNDER II'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2010 TJ NAREN',
    tournament: Tournament['2010 TJ NAREN'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2010 T-Party',
    tournament: Tournament['2010 T-Party'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 VCU Open (Saturday)',
    tournament: Tournament['2010 VCU Open (Saturday)'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 VCU Open (Sunday)',
    tournament: Tournament['2010 VCU Open (Sunday)'],
    year: 2010,
  },
  {
    difficulty: Difficulty.Open,
    label: '2010 Wild Kingdom',
    tournament: Tournament['2010 Wild Kingdom'],
    year: 2010,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2009 ACF Fall',
    tournament: Tournament['2009 ACF Fall'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2009 ACF Nationals',
    tournament: Tournament['2009 ACF Nationals'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2009 ACF Regionals',
    tournament: Tournament['2009 ACF Regionals'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2009 ACF Winter',
    tournament: Tournament['2009 ACF Winter'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2009 ACF Winter ',
    tournament: Tournament['2009 ACF Winter '],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 BATE',
    tournament: Tournament['2009 BATE'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 Chicago Open',
    tournament: Tournament['2009 Chicago Open'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 Chicago Open Literature',
    tournament: Tournament['2009 Chicago Open Literature'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2009 Chipola Lit + Fine Arts',
    tournament: Tournament['2009 Chipola Lit + Fine Arts'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 DAFT',
    tournament: Tournament['2009 DAFT'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2009 Fall Kickoff Tournament',
    tournament: Tournament['2009 Fall Kickoff Tournament'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Easy High School'],
    label: '2009 Fall Novice',
    tournament: Tournament['2009 Fall Novice'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2009 FICHTE',
    tournament: Tournament['2009 FICHTE'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2009 From Here To Eternity',
    tournament: Tournament['2009 From Here To Eternity'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 Gaddis II',
    tournament: Tournament['2009 Gaddis II'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 Geography Monstrosity',
    tournament: Tournament['2009 Geography Monstrosity'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2009 HFT',
    tournament: Tournament['2009 HFT'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 HSAPQ 4Q1',
    tournament: Tournament['2009 HSAPQ 4Q1'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 HSAPQ 4Q2',
    tournament: Tournament['2009 HSAPQ 4Q2'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 HSAPQ NASAT Tryout Set',
    tournament: Tournament['2009 HSAPQ NASAT Tryout Set'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 HSAPQ Tournament 10',
    tournament: Tournament['2009 HSAPQ Tournament 10'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 HSAPQ Tournament 11',
    tournament: Tournament['2009 HSAPQ Tournament 11'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 HSAPQ Tournament 8',
    tournament: Tournament['2009 HSAPQ Tournament 8'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 HSAPQ Tournament 9',
    tournament: Tournament['2009 HSAPQ Tournament 9'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 Mahfouz Memorial Lit',
    tournament: Tournament['2009 Mahfouz Memorial Lit'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 Minnesota Open KLEE Fine Arts',
    tournament: Tournament['2009 Minnesota Open KLEE Fine Arts'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 Minnesota Open Lit',
    tournament: Tournament['2009 Minnesota Open Lit'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2009 MUT',
    tournament: Tournament['2009 MUT'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 MW GSAC XVII',
    tournament: Tournament['2009 MW GSAC XVII'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2009 NTV',
    tournament: Tournament['2009 NTV'],
    year: 2009,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2009 PACE NSC',
    tournament: Tournament['2009 PACE NSC'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2009 Prison Bowl',
    tournament: Tournament['2009 Prison Bowl'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 RMP Fest',
    tournament: Tournament['2009 RMP Fest'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 The Experiment II',
    tournament: Tournament['2009 The Experiment II'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2009 THUNDER',
    tournament: Tournament['2009 THUNDER'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 Tyrone Slothrop Literature Singles',
    tournament: Tournament['2009 Tyrone Slothrop Literature Singles'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2009 U. of Georgia CCC',
    tournament: Tournament['2009 U. of Georgia CCC'],
    year: 2009,
  },
  {
    difficulty: Difficulty.Open,
    label: '2009 VCU Open',
    tournament: Tournament['2009 VCU Open'],
    year: 2009,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2008 ACF Fall',
    tournament: Tournament['2008 ACF Fall'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2008 ACF Fall ',
    tournament: Tournament['2008 ACF Fall '],
    year: 2008,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2008 ACF Nationals',
    tournament: Tournament['2008 ACF Nationals'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2008 ACF Regionals',
    tournament: Tournament['2008 ACF Regionals'],
    year: 2008,
  },
  {
    difficulty: Difficulty.Open,
    label: '2008 Chicago Open Literature',
    tournament: Tournament['2008 Chicago Open Literature'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2008 Chitin',
    tournament: Tournament['2008 Chitin'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Hard College'],
    label: '2008 FICHTE',
    tournament: Tournament['2008 FICHTE'],
    year: 2008,
  },
  {
    difficulty: Difficulty.Open,
    label: '2008 Gaddis I',
    tournament: Tournament['2008 Gaddis I'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2008 HFT',
    tournament: Tournament['2008 HFT'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2008 HSAPQ 4Q 1',
    tournament: Tournament['2008 HSAPQ 4Q 1'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2008 HSAPQ ACF 1',
    tournament: Tournament['2008 HSAPQ ACF 1'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2008 HSAPQ ACF 2',
    tournament: Tournament['2008 HSAPQ ACF 2'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2008 HSAPQ ACF 3',
    tournament: Tournament['2008 HSAPQ ACF 3'],
    year: 2008,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2008 HSAPQ NSC 1',
    tournament: Tournament['2008 HSAPQ NSC 1'],
    year: 2008,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2008 HSAPQ NSC 2',
    tournament: Tournament['2008 HSAPQ NSC 2'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Easy College'],
    label: '2008 MUT',
    tournament: Tournament['2008 MUT'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2008 NNT',
    tournament: Tournament['2008 NNT'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2008 NTV',
    tournament: Tournament['2008 NTV'],
    year: 2008,
  },
  {
    difficulty: Difficulty['National High School'],
    label: '2008 PACE NSC',
    tournament: Tournament['2008 PACE NSC'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Hard High School'],
    label: '2008 Prison Bowl',
    tournament: Tournament['2008 Prison Bowl'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Regular High School'],
    label: '2008 QuAC I',
    tournament: Tournament['2008 QuAC I'],
    year: 2008,
  },
  {
    difficulty: Difficulty.Open,
    label: '2008 RMP Fest',
    tournament: Tournament['2008 RMP Fest'],
    year: 2008,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2007 ACF Regionals',
    tournament: Tournament['2007 ACF Regionals'],
    year: 2007,
  },
  {
    difficulty: Difficulty.Open,
    label: '2007 The Experiment',
    tournament: Tournament['2007 The Experiment'],
    year: 2007,
  },
  {
    difficulty: Difficulty['Regular College'],
    label: '2006 ACF Regionals',
    tournament: Tournament['2006 ACF Regionals'],
    year: 2006,
  },
  {
    difficulty: Difficulty.Open,
    label: '2005 Teitler Myth Singles',
    tournament: Tournament['2005 Teitler Myth Singles'],
    year: 2005,
  },
];

export const CATEGORY_METADATA_BY_CATEGORY = objectPullWithKey(
  CATEGORIES,
  (categoryMetadata) => categoryMetadata,
  ({ category }) => category,
);

export const SUBCATEGORY_METADATA_BY_SUBCATEGORY = objectPullWithKey(
  SUBCATEGORIES,
  (subcategoryMetadata) => subcategoryMetadata,
  ({ subcategory }) => subcategory,
);

export const TOURNAMENT_METADATA_BY_TOURNAMENT = objectPullWithKey(
  TOURNAMENTS,
  (tournamentMetadata) => tournamentMetadata,
  ({ tournament }) => tournament,
);

export const DIFFICULTY_METADATA_BY_DIFFICULTY = objectPullWithKey(
  DIFFICULTIES,
  (difficultyMetadata) => difficultyMetadata,
  ({ difficulty }) => difficulty,
);
