name: build-and-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create .env file
        run: |
          touch .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo PGHOST=${{ secrets.PGHOST }} >> .env
          echo PGDATABASE=${{ secrets.PGDATABASE }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo PGUSER=${{ secrets.PGUSER }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo PGPASSWORD=${{ secrets.PGPASSWORD }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo PGPORT=${{ secrets.PGPORT }} >> .env
          echo NGINX_HOST=${{ secrets.NGINX_HOST }} >> .env
          echo NODE_HOST=${{ secrets.NODE_HOST }} >> .env
          echo NODE_PORT=${{ secrets.NODE_PORT }} >> .env
          echo LOGFLARE_API_KEY=${{ secrets.LOGFLARE_API_KEY }} >> .env
          echo LOGFLARE_SERVER_DEV_ID=${{ secrets.LOGFLARE_SERVER_DEV_ID }} >> .env
          echo LOGFLARE_SERVER_PROD_ID=${{ secrets.LOGFLARE_SERVER_PROD_ID }} >> .env
          echo DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} >> .env
          echo DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }} >> .env

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dependencies
        run: yarn install

      - name: build project
        run: yarn build

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build docker images
        run: docker-compose build

      - name: push docker images
        run: |
          docker push seanye24/qbhub-node:latest
          docker push seanye24/qbhub-nginx:latest
          docker push seanye24/qbhub-postgres:latest
