name: code-check
on: push

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: install dependencies
        run: yarn install

      - name: lint check
        run: yarn lint

      - name: formatting check
        run: npx prettier --check packages/*/src/*.{ts,tsx}

      - name: build check
        run: yarn build
