name: deploy-beta
on: workflow_dispatch
jobs:
  deploy-beta:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create .env file
        run: |
          touch .env
          echo PGHOST=${{ secrets.PGHOST }} >> .env
          echo PGDATABASE=${{ secrets.PGDATABASE }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo PGUSER=${{ secrets.PGUSER }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo PGPASSWORD=${{ secrets.PGPASSWORD }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo PGPORT=${{ secrets.PGPORT }} >> .env
          echo NGINX_HOST=${{ secrets.NGINX_BETA_HOST }} >> .env
          echo NODE_HOST=${{ secrets.NODE_HOST }} >> .env
          echo NODE_PORT=${{ secrets.NODE_PORT }} >> .env
          echo LOGFLARE_API_KEY=${{ secrets.LOGFLARE_API_KEY }} >> .env
          echo LOGFLARE_SERVER_PROD_ID=${{ secrets.LOGFLARE_SERVER_PROD_ID }} >> .env

      - name: copy files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_BETA_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_KEY }}
          source: 'docker-compose.yml,.env'
          target: '~'

      - name: deploy containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_BETA_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_KEY }}
          script: |
            docker compose down
            docker compose pull
            docker system prune --force
            docker compose up --detach
