name: static-analysis
on: push
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dependencies
        run: yarn install

      - name: lint files
        run: yarn lint

      - name: check formatting
        run: npx prettier --check packages/*/src/*.{ts,tsx}
